/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ADatePicker: typeof import('ant-design-vue/es/date-picker/dayjs')['default']
    ADescriptions: typeof import('ant-design-vue/es')['Descriptions']
    ADescriptionsItem: typeof import('ant-design-vue/es')['DescriptionsItem']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARangePicker: typeof import('ant-design-vue/es/date-picker/dayjs')['RangePicker']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    BusinessCategoryForm: typeof import('./src/components/BusinessCategoryForm.vue')['default']
    ColumnConfig: typeof import('./src/components/ColumnConfig.vue')['default']
    CustomerForm: typeof import('./src/components/CustomerForm.vue')['default']
    DeliveryExpenseReportPrint: typeof import('./src/components/DeliveryExpenseReportPrint.vue')['default']
    DeliveryOrderDetail: typeof import('./src/components/DeliveryOrderDetail.vue')['default']
    DeliveryOrderForm: typeof import('./src/components/DeliveryOrderForm.vue')['default']
    DeliveryOrderPrint: typeof import('./src/components/DeliveryOrderPrint.vue')['default']
    InventoryReportPrint: typeof import('./src/components/InventoryReportPrint.vue')['default']
    PaymentMethodForm: typeof import('./src/components/PaymentMethodForm.vue')['default']
    ProductClassificationDetail: typeof import('./src/components/ProductClassificationDetail.vue')['default']
    ProductForm: typeof import('./src/components/ProductForm.vue')['default']
    PurchaseOrderDetail: typeof import('./src/components/PurchaseOrderDetail.vue')['default']
    PurchaseOrderForm: typeof import('./src/components/PurchaseOrderForm.vue')['default']
    PurchaseOrderPrint: typeof import('./src/components/PurchaseOrderPrint.vue')['default']
    PurchaseOrderPrintEn: typeof import('./src/components/PurchaseOrderPrintEn.vue')['default']
    QuotationForm: typeof import('./src/components/QuotationForm.vue')['default']
    QuotationPrint: typeof import('./src/components/QuotationPrint.vue')['default']
    QuotationPrintEn: typeof import('./src/components/QuotationPrintEn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesOrderDetail: typeof import('./src/components/SalesOrderDetail.vue')['default']
    SalesOrderForm: typeof import('./src/components/SalesOrderForm.vue')['default']
    SalesOrderPrint: typeof import('./src/components/SalesOrderPrint.vue')['default']
    SupplierForm: typeof import('./src/components/SupplierForm.vue')['default']
    WarehousingExpenseReportPrint: typeof import('./src/components/WarehousingExpenseReportPrint.vue')['default']
    WarehousingOrderDetail: typeof import('./src/components/WarehousingOrderDetail.vue')['default']
    WarehousingOrderForm: typeof import('./src/components/WarehousingOrderForm.vue')['default']
    WarehousingOrderPrint: typeof import('./src/components/WarehousingOrderPrint.vue')['default']
  }
}
